Repository fga-eps-mds/2022-1-Visualeasy-Frontend, pull requests merged in 2022-08, with the labels that each got.

#57 45 gerar grafico
  __tests__/home.test.jsx
  __tests__/index.test.jsx
  package-lock.json
  package.json
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
  src/pages/components/Sidebar/logo-retangular.png
  src/pages/index.tsx
  src/public/logo-quadrada.png
  yarn.lock
Labels: Front-end, Release 1

#58 Merge Devel to Main R1
  README.md
  __tests__/home.test.jsx
  __tests__/index.test.jsx
  heroku.yml
  package-lock.json
  package.json
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
  src/pages/components/Sidebar/logo-retangular.png
  src/pages/index.tsx
  src/public/logo-quadrada.png
  yarn.lock
Labels: DEVOPS, ANALYTICS, EPS, Release 1

#62 ajustando o tamanho da imagem
  public/favicon.ico
  public/images/logo-quadrada.png
  public/images/logo-retangular.png
  public/vercel.svg
  src/pages/components/Sidebar/index.tsx
  yarn.lock
Labels: bug, HOTFIX

#63 Us03 buscar variaveis
  .gitignore
  __tests__/home.test.jsx
  package-lock.json
  package.json
  src/pages/api/api.ts
  src/pages/api/hello.ts
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Sidebar/index.tsx
  yarn.lock
Labels: FEATURE, EPS, Front-end, Release 1

#65 Us05 intervalo tempo
  __tests__/home.test.jsx
Labels: FEATURE, MEDIUM, EPS, Front-end

#64 Us05 us07 gerar grafico int tempo
  __tests__/home.test.jsx
  src/pages/api/api.ts
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/RatioTimeChart/Index.tsx
  src/pages/components/Sidebar/index.tsx
Labels: FEATURE, HARD, EPS, Front-end

#66 Us06 selecionar intervalo
  __tests__/home.test.jsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/RatioTimeChart/Index.tsx
  src/pages/components/Sidebar/index.tsx
Labels: FEATURE, EPS, Front-end

#67 Create CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: DOCS

#68 Merge Devel to Main R2
  .gitignore
  CONTRIBUTING.md
  __tests__/home.test.jsx
  package-lock.json
  package.json
  public/favicon.ico
  public/images/logo-quadrada.png
  public/images/logo-retangular.png
  public/vercel.svg
  src/pages/api/api.ts
  src/pages/api/hello.ts
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/RatioTimeChart/Index.tsx
  src/pages/components/Sidebar/index.tsx
  yarn.lock
Labels: DEVOPS, ANALYTICS, EPS, Front-end, Release 2

#71 Us11 print grafico
  __tests__/home.test.jsx
  public/images/screenshot-icon.svg
  src/pages/api/api.ts
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/Graph/index.tsx
Labels: FEATURE, EPS, Front-end

#72 Us08 mult variaveis
  .github/workflows/release.yml
  __tests__/home.test.jsx
  src/pages/api/api.ts
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/RatioTimeChart/Index.tsx
Labels: FEATURE, EPS, Front-end

#74 Retirando arquivos desnecessários da rotina de testes.
  jest.config.js
  sonar-project.properties
Labels: HOTFIX, Front-end

#75 Hotfix change buttons css
  src/pages/components/Graph/index.tsx
Labels: HOTFIX, EPS, Front-end

#77 Devops deploy04
  .github/workflows/build.yml
  src/pages/api/api.ts
Labels: HOTFIX, DEVOPS, EPS, Front-end
