Repository fga-eps-mds/2022-1-Visualeasy-Frontend, pull requests merged in 2022-09, with the labels that each got.

#79 Us09 visualizar varios graficos
  .gitignore
  __tests__/home.test.jsx
  package.json
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
Labels: FEATURE, US, HARD, EPS, Front-end

#80 Us13 link compartilhamento
  package.json
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
  src/pages/index.tsx
Labels: FEATURE, US, HARD, EPS, Front-end

#81 us15 - Criando botão tela cheia
  src/pages/components/Sidebar/index.tsx
Labels: FEATURE, MEDIUM, EPS

#83 Merge Devel to Main R4
  .github/workflows/release.yml
  .github/workflows/release_tag.yml
  .gitignore
  jest.config.js
  package.json
  src/pages/components/DisplayHome/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
  src/pages/index.tsx
Labels: DEVOPS, ANALYTICS, EPS, Release 4

#84 Remoção dos Comentários
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .gitignore
  Dockerfile
  __tests__/home.test.jsx
  jest.config.js
  next-env.d.ts
  sonar-project.properties
  src/pages/_document.tsx
  src/pages/api/api.ts
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/RatioTimeChart/Index.tsx
  src/pages/components/Sidebar/index.tsx
  src/pages/index.tsx
Labels: bug

#85 Validações no Frontend
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
Labels: bug, enhancement, HOTFIX, EPS, Front-end

#86 Bugfix testes
  .github/workflows/build.yml
  .gitignore
  README.md
  __tests__/__snapshots__/home.test.jsx.snap
  __tests__/home.test.jsx
  next-env.d.ts
  package.json
  src/pages/api/api.ts
  src/pages/components/Sidebar/index.tsx
Labels: HOTFIX, EPS, Front-end

#87 Melhorias
  __tests__/__snapshots__/home.test.jsx.snap
  __tests__/home.test.jsx
  src/pages/components/FormGraph/index.tsx
  src/pages/components/Graph/index.tsx
  src/pages/components/Sidebar/index.tsx
Labels: HOTFIX, EPS, Front-end
